/**
 * Shared git helpers — branch setup, diff collection, commit + patch saving.
 * Used by both integration and coder skills.
 */

import fs from "node:fs";
import path from "node:path";
import simpleGit from "simple-git";
import { PATCHES_DIR, REPOS, type RepoKey } from "../../config.js";

/** Set up a feature branch in a repo, returning git handle + default branch. */
export async function setupBranch(
  repoKey: RepoKey,
  branchName: string,
): Promise<{ git: ReturnType<typeof simpleGit>; defaultBranch: string }> {
  const repoDir = REPOS[repoKey].dir;
  const git = simpleGit(repoDir);

  await git.raw(["checkout", "--force", "HEAD"]);
  const defaultBranch = (await git.branch()).current || "main";

  try {
    await git.deleteLocalBranch(branchName, true);
  } catch { /* branch didn't exist */ }
  await git.checkoutLocalBranch(branchName);

  return { git, defaultBranch };
}

/** Stage everything and return the combined diff + file count. */
export async function collectDiff(
  git: ReturnType<typeof simpleGit>,
): Promise<{ diff: string; fileCount: number }> {
  await git.add(".");
  const diff = await git.diff(["HEAD"]);
  const stat = await git.diffSummary(["HEAD"]);
  return { diff, fileCount: stat.files.length };
}

/**
 * Commit changes on the feature branch, save a patch file, then
 * checkout back to the default branch.
 */
export async function commitAndSave(
  git: ReturnType<typeof simpleGit>,
  defaultBranch: string,
  taskLabel: string,
  repoKey: RepoKey,
  slug: string,
  diff: string,
  /** Prefix for the patch file name (e.g. "integration", "coder"). */
  patchPrefix = "integration",
): Promise<void> {
  const patchPath = path.join(PATCHES_DIR, `${patchPrefix}-${slug}-${repoKey}.patch`);
  fs.mkdirSync(path.dirname(patchPath), { recursive: true });
  fs.writeFileSync(patchPath, diff);

  await git.add(".");
  await git.commit(`feat: ${taskLabel}\n\nGenerated by Agent-Control-Center`);
  await git.checkout(defaultBranch);
}
