/**
 * Shared git helpers — branch setup, diff collection, commit + patch saving.
 * Used by both sdk-integrator and coder skills.
 */

import fs from "node:fs";
import path from "node:path";
import simpleGit from "simple-git";
import { PATCHES_DIR, REPOS, type ExtendedRepoKey } from "../../config.js";

// Paths we refuse to record — lock files regenerate downstream and their
// churn drowns out the real code changes in review.
const IGNORED_PATHSPECS = [":(glob)**/yarn.lock"];

/** Revert any modifications to ignored paths back to HEAD before staging. */
async function discardIgnoredPaths(
  git: ReturnType<typeof simpleGit>,
): Promise<void> {
  for (const spec of IGNORED_PATHSPECS) {
    try {
      await git.raw(["checkout", "HEAD", "--", spec]);
    } catch {
      /* pathspec may not match anything in this repo — fine */
    }
  }
}

/** Set up a feature branch in a repo, returning git handle + default branch. */
export async function setupBranch(
  repoKey: ExtendedRepoKey,
  branchName: string,
): Promise<{ git: ReturnType<typeof simpleGit>; defaultBranch: string }> {
  const repoDir = REPOS[repoKey].dir;
  const git = simpleGit(repoDir);

  await git.raw(["checkout", "--force", "HEAD"]);
  let currentBranch = (await git.branch()).current || "main";

  // If we're sitting on the feature branch from a prior run, hop off so we can
  // recreate it cleanly. Resolve a sane default to land on.
  if (currentBranch === branchName) {
    const branches = await git.branch();
    const fallback =
      ["main", "master", "develop"].find((b) => branches.all.includes(b)) ||
      branches.all.find((b) => b !== branchName) ||
      "main";
    await git.checkout(fallback);
    currentBranch = fallback;
  }
  const defaultBranch = currentBranch;

  // -B creates the branch or resets it if it already exists.
  await git.checkout(["-B", branchName]);

  return { git, defaultBranch };
}

/** Stage everything and return the combined diff + file count. */
export async function collectDiff(
  git: ReturnType<typeof simpleGit>,
): Promise<{ diff: string; fileCount: number }> {
  await discardIgnoredPaths(git);
  await git.add(".");
  const diff = await git.diff(["HEAD"]);
  const stat = await git.diffSummary(["HEAD"]);
  return { diff, fileCount: stat.files.length };
}

/**
 * Commit changes on the feature branch, save a patch file, then
 * checkout back to the default branch.
 */
export async function commitAndSave(
  git: ReturnType<typeof simpleGit>,
  defaultBranch: string,
  taskLabel: string,
  repoKey: ExtendedRepoKey,
  slug: string,
  diff: string,
  /** Prefix for the patch file name (e.g. "integration", "coder"). */
  patchPrefix = "integration",
): Promise<void> {
  const patchPath = path.join(PATCHES_DIR, `${patchPrefix}-${slug}-${repoKey}.patch`);
  fs.mkdirSync(path.dirname(patchPath), { recursive: true });
  fs.writeFileSync(patchPath, diff);

  await discardIgnoredPaths(git);
  await git.add(".");
  await git.commit(`feat: ${taskLabel}\n\nGenerated by Agent-Control-Center`);
  await git.checkout(defaultBranch);
}
