import { Router } from "express";
import fs from "node:fs";
import path from "node:path";
import { PATCHES_DIR, REPOS, type RepoKey } from "../config.js";
import { db, nowIso, type GapRow } from "../db.js";
import { ask, askStream } from "../llm.js";
import { generateDoc } from "../skills/docs/generator.js";
import simpleGit from "simple-git";
import { commitWithSubmodules, getDiffWithSubmodules, resetSubmodules, forceCheckoutBranch } from "../skills/submoduleGit.js";
import { runRescriptBuild } from "../skills/buildCheck.js";
import { pushBranchToFork, createPullRequest, formatPrBody, pushSubmoduleToFork, rewriteGitmodulesToForks, commitsAheadOfForkMain } from "../skills/githubPr.js";
import { withRepoLock } from "../workspace/mutex.js";

export const patchesRouter = Router();

/**
 * Generate a patch for a verified gap (blocking, legacy).
 * Kept for backward compatibility — new callers use /patch/stream.
 */
patchesRouter.post("/gaps/:id/patch", async (req, res) => {
  const gapId = Number(req.params.id);
  if (!Number.isFinite(gapId)) {
    return res.status(400).json({ error: "bad id" });
  }

  const gap = db.prepare("SELECT * FROM gaps WHERE id = ?").get(gapId) as
    | GapRow
    | undefined;
  if (!gap) return res.status(404).json({ error: "gap not found" });

  const existing = db
    .prepare(
      `SELECT p.* FROM patches p
       WHERE p.gap_id = ?
       UNION
       SELECT p.* FROM patches p
       JOIN gaps g ON g.id = p.gap_id
       WHERE g.canonical_name = ? AND g.category = ? AND g.missing_in = ?
       LIMIT 1`,
    )
    .get(gapId, gap.canonical_name, gap.category, gap.missing_in);
  if (existing) {
    return res.status(409).json({ error: "patch already exists", patch: existing });
  }

  const targetRepo = gap.missing_in as RepoKey;
  const sourceRepo = gap.present_in as RepoKey;
  const targetDir = REPOS[targetRepo].dir;
  const sourceDir = REPOS[sourceRepo].dir;

  try {
    await withRepoLock(targetRepo, async () => {
    const evidence = safeParseEvidence(gap.evidence);
    const sourceFile = evidence?.[0]?.file;
    let sourceContext = "";
    if (sourceFile) {
      const fullPath = path.join(sourceDir, sourceFile);
      try {
        sourceContext = fs.readFileSync(fullPath, "utf8");
        if (sourceContext.length > 8000) {
          sourceContext = sourceContext.slice(0, 8000) + "\n... [truncated]";
        }
      } catch {
        sourceContext = `(could not read ${sourceFile})`;
      }
    }

    const git = simpleGit(targetDir);
    const slug = gap.canonical_name
      .replace(/[^a-z0-9]+/gi, "-")
      .slice(0, 40)
      .replace(/-$/, "");
    const branchName = `feat/gap-${gapId}-${slug}`;
    const defaultBranch = "main";

    await resetSubmodules(targetDir, targetRepo);
    await forceCheckoutBranch(targetDir, targetRepo, defaultBranch);
    try { await git.deleteLocalBranch(branchName, true); } catch { /* didn't exist */ }
    await git.checkoutLocalBranch(branchName);

    const repoLabel =
      targetRepo === "web"
        ? "hyperswitch-web (ReScript web SDK)"
        : "hyperswitch-client-core (ReScript mobile SDK)";
    const sourceLabel =
      sourceRepo === "web"
        ? "hyperswitch-web (ReScript web SDK)"
        : "hyperswitch-client-core (ReScript mobile SDK)";

    const prompt = buildSingleAgentPrompt({
      gap, targetRepo, sourceRepo, repoLabel, sourceLabel,
      sourceDir, targetDir, sourceFile: sourceFile ?? null,
      sourceContext,
    });

    const summary = await ask(prompt, {
      model: "opus",
      timeoutMs: 1_500_000,
      cwd: targetDir,
      allowedTools: ["Edit", "Write", "Read", "Glob", "Grep", "Bash"],
    });

    const { diff, fileCount } = await getDiffWithSubmodules(targetDir, targetRepo);

    if (!diff || fileCount === 0) {
      await forceCheckoutBranch(targetDir, targetRepo, defaultBranch);
      try { await git.deleteLocalBranch(branchName, true); } catch { /* */ }
      return res.status(422).json({ error: "Opus did not produce any file changes", summary });
    }

    const patchFileName = `${gapId}-${slug}.patch`;
    const patchPath = path.join(PATCHES_DIR, patchFileName);
    fs.writeFileSync(patchPath, diff);

    const build = runRescriptBuild(targetDir);
    if (!build.passed) {
      await forceCheckoutBranch(targetDir, targetRepo, defaultBranch);
      try { await git.deleteLocalBranch(branchName, true); } catch { /* */ }
      return res.status(422).json({
        error: "ReScript build failed — patch rejected.",
        buildStatus: "fail",
        buildLog: build.log,
        diff,
        summary: summary.slice(0, 2000),
        patchPath,
      });
    }

    const commitMsg = `feat: add ${gap.canonical_name}\n\nGenerated by feature-gap-dashboard for gap #${gapId}`;
    const commitResult = await commitWithSubmodules(targetDir, targetRepo, commitMsg);

    const aheadCount = await commitsAheadOfForkMain(targetDir, branchName);
    if (aheadCount === 0 && commitResult.submodulesChanged.length === 0) {
      await forceCheckoutBranch(targetDir, targetRepo, defaultBranch);
      try { await git.deleteLocalBranch(branchName, true); } catch { /* */ }
      return res.status(500).json({ error: "commitWithSubmodules produced zero commits", diff, summary: summary.slice(0, 2000), patchPath });
    }

    let prUrl: string | null = null;
    let prNumber: number | null = null;
    let prWarning: string | null = null;
    const submodulePushSummaries: string[] = [];
    try {
      for (const subDir of commitResult.submodulesChanged) {
        const result = await pushSubmoduleToFork({ parentDir: targetDir, subDir, branchName });
        submodulePushSummaries.push(`${subDir} → ${result.forkUrl} @ ${result.sha.slice(0, 8)}`);
      }
      if (commitResult.submodulesChanged.length > 0) {
        const rewritten = rewriteGitmodulesToForks(targetDir, commitResult.submodulesChanged);
        if (rewritten.length > 0) {
          const parentGit = simpleGit(targetDir);
          await parentGit.add([".gitmodules"]);
          await parentGit.commit(`chore: point submodules at bot forks for build\n\nRewritten: ${rewritten.join(", ")}`);
        }
      }
      await pushBranchToFork(targetDir, targetRepo, branchName);
      const body = formatPrBody({ gapId, canonicalName: gap.canonical_name, category: gap.category, rationale: gap.rationale, summaryJson: summary, filesTouched: fileCount, buildLog: build.log, submodulePushes: submodulePushSummaries });
      const created = await createPullRequest({ repoKey: targetRepo, branch: branchName, title: `feat: add ${gap.canonical_name}`, body });
      prUrl = created.prUrl;
      prNumber = created.prNumber;
    } catch (err) {
      prWarning = `PR creation failed: ${(err as Error).message}`;
      console.error(`[patches] PR creation failed for gap ${gapId}:`, err);
    }

    await forceCheckoutBranch(targetDir, targetRepo, defaultBranch);

    const patchRow = db
      .prepare(`INSERT INTO patches (gap_id, repo, branch, diff_path, summary, files_touched, status, created_at, build_status, build_log, pr_url, pr_number, pr_warning) VALUES (?, ?, ?, ?, ?, ?, 'generated', ?, ?, ?, ?, ?, ?)`)
      .run(gapId, targetRepo, branchName, patchPath, summary.slice(0, 2000), fileCount, nowIso(), "pass", build.log, prUrl, prNumber, prWarning);

    res.json({ patchId: patchRow.lastInsertRowid, branch: branchName, repo: targetRepo, filesTouched: fileCount, summary: summary.slice(0, 2000), diff, buildStatus: "pass", buildLog: build.log, prUrl, prNumber, prWarning });
    });
  } catch (err) {
    console.error(`[patches] failed for gap ${gapId}:`, err);
    try { await withRepoLock(targetRepo, () => forceCheckoutBranch(targetDir, targetRepo, "main")); } catch { /* best effort */ }
    res.status(500).json({ error: (err as Error).message });
  }
});

/**
 * Multi-Opus streaming patch generation.
 * POST /gaps/:id/patch/stream
 *
 * Three specialized sub-agents run in sequence:
 *
 *   Agent 1 — Source Analyst (READ-ONLY, cwd=sourceDir)
 *     Explores the source repo and produces a structured JSON spec:
 *     featureName, typeDefinition, configKey, defaultValue, behavior, allRelatedFiles,
 *     reScriptGotchas, implementationSteps
 *
 *   Agent 2 — Implementer (cwd=targetDir)
 *     Receives the spec and implements the feature. Runs re:build after edits,
 *     iterates until green. No attempt limit.
 *
 *   Agent 3 — Verifier (READ-ONLY, cwd=targetDir)
 *     Checks that the implementation matches the spec — types, config keys,
 *     default values. Build is already confirmed green by the server; verifier
 *     checks semantic correctness.
 *
 * Phase boundaries are emitted as {type:"phase_marker",phase:"analysing"|"implementing"|"verifying"}.
 * Final line is always {type:"patch_done",...} or {type:"error",...}.
 */
patchesRouter.post("/gaps/:id/patch/stream", async (req, res) => {
  const gapId = Number(req.params.id);
  if (!Number.isFinite(gapId)) {
    return res.status(400).json({ error: "bad id" });
  }

  const gap = db.prepare("SELECT * FROM gaps WHERE id = ?").get(gapId) as
    | GapRow
    | undefined;
  if (!gap) return res.status(404).json({ error: "gap not found" });

  const existing = db
    .prepare(
      `SELECT p.* FROM patches p
       WHERE p.gap_id = ?
       UNION
       SELECT p.* FROM patches p
       JOIN gaps g ON g.id = p.gap_id
       WHERE g.canonical_name = ? AND g.category = ? AND g.missing_in = ?
       LIMIT 1`,
    )
    .get(gapId, gap.canonical_name, gap.category, gap.missing_in);
  if (existing) {
    return res.status(409).json({ error: "patch already exists", patch: existing });
  }

  const targetRepo = gap.missing_in as RepoKey;
  const sourceRepo = gap.present_in as RepoKey;
  const targetDir = REPOS[targetRepo].dir;
  const sourceDir = REPOS[sourceRepo].dir;

  res.setHeader("Content-Type", "application/x-ndjson");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("X-Accel-Buffering", "no");
  res.flushHeaders();

  let clientClosed = false;
  req.on("close", () => { clientClosed = true; });

  const writeLine = (obj: unknown) => {
    if (!clientClosed && !res.writableEnded) {
      res.write(JSON.stringify(obj) + "\n");
    }
  };

  const repoLabel =
    targetRepo === "web"
      ? "hyperswitch-web (ReScript web SDK)"
      : "hyperswitch-client-core (ReScript mobile SDK)";
  const sourceLabel =
    sourceRepo === "web"
      ? "hyperswitch-web (ReScript web SDK)"
      : "hyperswitch-client-core (ReScript mobile SDK)";

  try {
    await withRepoLock(targetRepo, async () => {
      const evidence = safeParseEvidence(gap.evidence);
      const sourceFile = evidence?.[0]?.file;

      const git = simpleGit(targetDir);
      const slug = gap.canonical_name
        .replace(/[^a-z0-9]+/gi, "-")
        .slice(0, 40)
        .replace(/-$/, "");
      const branchName = `feat/gap-${gapId}-${slug}`;

      await resetSubmodules(targetDir, targetRepo);
      await forceCheckoutBranch(targetDir, targetRepo, "main");
      try { await git.deleteLocalBranch(branchName, true); } catch { /* */ }
      await git.checkoutLocalBranch(branchName);

      const sourceEntryPath = sourceFile
        ? `${sourceDir}/${sourceFile}`
        : `${sourceDir} (discover the entry point with Grep)`;

      // ================================================================
      // AGENT 1 — SOURCE ANALYST (read-only, cwd=sourceDir)
      // ================================================================
      writeLine({ type: "phase_marker", phase: "analysing" });

      const analystPrompt = `You are a source-code analyst working exclusively in read-only mode.

Your task: fully analyse how the feature "${gap.canonical_name}" works in the ${sourceLabel} repo.

Source repo: ${sourceDir}
Entry point: ${sourceEntryPath}

INSTRUCTIONS:
1. Start from the entry point above. Read it completely.
2. Follow every import and cross-reference to find ALL files involved in this feature:
   - Where is the TYPE declared? (Record field, option type, variant)
   - Where is it PARSED from the JS/JSON config object? (Which function reads it?)
   - How does the value FLOW through the system? (config → state atom → component prop → render branch)
   - Which component or function RENDERS or BEHAVES differently based on this feature?
3. Run Grep across ${sourceDir} for "${gap.canonical_name}" and related camelCase/snake_case variants to find any callsites you missed.
4. Check for ReScript-specific patterns:
   - Is the field option<T> or a direct type?
   - Are there Belt.Option or pattern-match usages?
   - Are there any switch/match sites that would need a new branch?

OUTPUT: Produce ONLY valid JSON in this exact shape (no fences, no prose):
{
  "featureName": "${gap.canonical_name}",
  "typeDefinition": "<full ReScript type, e.g. option<bool>",
  "configKey": "<exact JS/JSON key integrators use, e.g. paymentMethodOrder>",
  "defaultValue": "<default when absent, e.g. None or false>",
  "behavior": "<what this feature does behaviourally when enabled/set>",
  "allRelatedFiles": [
    {"path": "<relative path from repo root>", "role": "<type|parser|state|component|util>"}
  ],
  "reScriptGotchas": ["<pitfall 1>", "<pitfall 2>"],
  "implementationSteps": [
    "<ordered step 1: e.g. Add field X to record Y in file Z>",
    "<ordered step 2: ...>"
  ]
}

Do NOT write any code in the target repo. Your cwd is ${sourceDir} — only read there.`;

      let specText = "";
      await askStream(
        analystPrompt,
        {
          model: "opus",
          cwd: sourceDir,
          allowedTools: ["Read", "Glob", "Grep"],
          timeoutMs: 600_000,
        },
        (chunk) => {
          writeLine(chunk);
          if (chunk.type === "text" && chunk.text) specText += chunk.text;
        },
      );

      // Extract JSON spec from analyst output (may be surrounded by thinking text)
      let spec: SourceSpec | null = null;
      try {
        const m = specText.match(/\{[\s\S]*\}/);
        if (m) spec = JSON.parse(m[0]) as SourceSpec;
      } catch {
        writeLine({ type: "text", text: "\n[Note: analyst output could not be parsed as JSON — using fallback prompt for implementer]\n" });
      }

      // ================================================================
      // AGENT 2 — IMPLEMENTER (cwd=targetDir, full tool access)
      // ================================================================
      writeLine({ type: "phase_marker", phase: "implementing" });

      let agentText = "";

      const implementerPrompt = spec
        ? buildSpecBasedImplementerPrompt({ spec, gap, repoLabel, sourceLabel, sourceDir, targetDir, sourceEntryPath })
        : buildFallbackImplementerPrompt({ gap, repoLabel, sourceLabel, sourceDir, targetDir, sourceEntryPath });

      await askStream(
        implementerPrompt,
        {
          model: "opus",
          cwd: targetDir,
          allowedTools: ["Edit", "Write", "Read", "Glob", "Grep", "Bash"],
          timeoutMs: 1_200_000,
        },
        (chunk) => {
          writeLine(chunk);
          if (chunk.type === "text" && chunk.text) agentText += chunk.text;
        },
      );

      // ================================================================
      // SERVER BUILD CHECK (hard gate — must pass before verifier runs)
      // ================================================================
      const { diff, fileCount } = await getDiffWithSubmodules(targetDir, targetRepo);

      if (!diff || fileCount === 0) {
        await forceCheckoutBranch(targetDir, targetRepo, "main");
        try { await git.deleteLocalBranch(branchName, true); } catch { /* */ }
        writeLine({ type: "error", error: "Agent did not produce any file changes" });
        res.end();
        return;
      }

      const patchFileName = `${gapId}-${slug}.patch`;
      const patchPath = path.join(PATCHES_DIR, patchFileName);
      fs.writeFileSync(patchPath, diff);

      writeLine({ type: "text", text: "\n---\nRunning server-side build verification…" });
      const build = runRescriptBuild(targetDir);
      if (!build.passed) {
        // Don't delete the branch — save a build_failed patch row so the chat
        // agent can checkout the branch and fix the errors interactively.
        await forceCheckoutBranch(targetDir, targetRepo, "main");

        const failedPatchRow = db
          .prepare(
            `INSERT INTO patches (gap_id, repo, branch, diff_path, summary, files_touched, status, created_at, build_status, build_log, pr_url, pr_number, pr_warning)
             VALUES (?, ?, ?, ?, ?, ?, 'build_failed', ?, 'fail', ?, NULL, NULL, NULL)`,
          )
          .run(
            gapId,
            targetRepo,
            branchName,
            patchPath,
            `Build failed during generation of ${gap.canonical_name}`,
            fileCount,
            nowIso(),
            build.log,
          );

        writeLine({
          type: "build_failed",
          patchId: Number(failedPatchRow.lastInsertRowid),
          branch: branchName,
          repo: targetRepo,
          buildLog: build.log.slice(-4000),
          diff,
          filesTouched: fileCount,
        });
        res.end();
        return;
      }

      // ================================================================
      // AGENT 3 — VERIFIER (read-only, cwd=targetDir)
      // Build is already green. Verifier checks semantic correctness only.
      // ================================================================
      writeLine({ type: "phase_marker", phase: "verifying" });

      const verifierPrompt = buildVerifierPrompt({ spec, gap, targetDir, repoLabel });

      let verifyText = "";
      await askStream(
        verifierPrompt,
        {
          model: "opus",
          cwd: targetDir,
          allowedTools: ["Read", "Grep", "Glob"],
          timeoutMs: 300_000,
        },
        (chunk) => {
          writeLine(chunk);
          if (chunk.type === "text" && chunk.text) verifyText += chunk.text;
        },
      );

      // Parse verifier result — default to pass if unparseable (build already confirmed)
      let verifyPassed = true;
      let verifyIssues: string[] = [];
      try {
        const m = verifyText.match(/\{[\s\S]*\}/);
        if (m) {
          const parsed = JSON.parse(m[0]) as { pass?: boolean; issues?: string[] };
          if (parsed.pass === false) {
            verifyPassed = false;
            verifyIssues = Array.isArray(parsed.issues) ? parsed.issues : ["unspecified issues"];
          }
        }
      } catch { /* default to pass — build gate is the hard gate */ }

      if (!verifyPassed) {
        await forceCheckoutBranch(targetDir, targetRepo, "main");
        try { await git.deleteLocalBranch(branchName, true); } catch { /* */ }
        writeLine({
          type: "error",
          error: `Verifier rejected the implementation:\n${verifyIssues.map((i) => `• ${i}`).join("\n")}\n\nThe build was green but the implementation doesn't match the spec. Regenerate with more context.`,
        });
        res.end();
        return;
      }

      writeLine({ type: "text", text: "\nBuild passed ✓  Verification passed ✓  Committing…" });

      // ================================================================
      // COMMIT + PUSH + PR
      // ================================================================
      const commitMsg = `feat: add ${gap.canonical_name}\n\nGenerated by feature-gap-dashboard for gap #${gapId}`;
      const commitResult = await commitWithSubmodules(targetDir, targetRepo, commitMsg);

      const aheadCount = await commitsAheadOfForkMain(targetDir, branchName);
      if (aheadCount === 0 && commitResult.submodulesChanged.length === 0) {
        await forceCheckoutBranch(targetDir, targetRepo, "main");
        try { await git.deleteLocalBranch(branchName, true); } catch { /* */ }
        writeLine({ type: "error", error: "commitWithSubmodules produced zero commits — staged paths may not match" });
        res.end();
        return;
      }

      writeLine({ type: "text", text: "Pushing to fork and opening PR…" });

      let prUrl: string | null = null;
      let prNumber: number | null = null;
      let prWarning: string | null = null;
      const submodulePushSummaries: string[] = [];
      try {
        for (const subDir of commitResult.submodulesChanged) {
          const result = await pushSubmoduleToFork({ parentDir: targetDir, subDir, branchName });
          submodulePushSummaries.push(`${subDir} → ${result.forkUrl} @ ${result.sha.slice(0, 8)}`);
        }
        if (commitResult.submodulesChanged.length > 0) {
          const rewritten = rewriteGitmodulesToForks(targetDir, commitResult.submodulesChanged);
          if (rewritten.length > 0) {
            const parentGit = simpleGit(targetDir);
            await parentGit.add([".gitmodules"]);
            await parentGit.commit(`chore: point submodules at bot forks for build\n\nAutomated by feature-gap-dashboard.\nRewritten: ${rewritten.join(", ")}`);
          }
        }
        await pushBranchToFork(targetDir, targetRepo, branchName);
        const body = formatPrBody({
          gapId,
          canonicalName: gap.canonical_name,
          category: gap.category,
          rationale: gap.rationale,
          summaryJson: agentText,
          filesTouched: fileCount,
          buildLog: build.log,
          submodulePushes: submodulePushSummaries,
        });
        const created = await createPullRequest({
          repoKey: targetRepo,
          branch: branchName,
          title: `feat: add ${gap.canonical_name}`,
          body,
        });
        prUrl = created.prUrl;
        prNumber = created.prNumber;
      } catch (err) {
        prWarning = `PR creation failed: ${(err as Error).message}`;
        console.error(`[patches/stream] PR creation failed for gap ${gapId}:`, err);
      }

      await forceCheckoutBranch(targetDir, targetRepo, "main");

      const patchRow = db
        .prepare(
          `INSERT INTO patches (gap_id, repo, branch, diff_path, summary, files_touched, status, created_at, build_status, build_log, pr_url, pr_number, pr_warning)
           VALUES (?, ?, ?, ?, ?, ?, 'generated', ?, ?, ?, ?, ?, ?)`,
        )
        .run(
          gapId,
          targetRepo,
          branchName,
          patchPath,
          agentText.slice(0, 2000),
          fileCount,
          nowIso(),
          "pass",
          build.log,
          prUrl,
          prNumber,
          prWarning,
        );

      const patchId = Number(patchRow.lastInsertRowid);

      writeLine({
        type: "patch_done",
        patchId,
        branch: branchName,
        repo: targetRepo,
        filesTouched: fileCount,
        summary: agentText.slice(0, 2000),
        diff,
        buildStatus: "pass",
        buildLog: build.log,
        prUrl,
        prNumber,
        prWarning,
      });

      // Fire-and-forget documentation generation
      generateDoc({
        sourceType: "patch",
        sourceId: patchId,
        diff,
        summary: agentText.slice(0, 2000),
        featureName: gap.canonical_name,
        filesChanged: diff.split("\n").filter((l: string) => l.startsWith("diff --git")).map((l: string) => l.replace(/^diff --git a\//, "").replace(/ b\/.*/, "")),
        repoKey: targetRepo,
      }).catch(() => { /* fire-and-forget */ });

      res.end();
    });
  } catch (err) {
    console.error(`[patches/stream] failed for gap ${gapId}:`, err);
    try { await withRepoLock(targetRepo, () => forceCheckoutBranch(targetDir, targetRepo, "main")); } catch { /* best effort */ }
    writeLine({ type: "error", error: (err as Error).message });
    if (!res.writableEnded) res.end();
  }
});

/** GET /patches/:id */
patchesRouter.get("/patches/:id", async (req, res) => {
  const patchId = Number(req.params.id);
  const row = db.prepare("SELECT * FROM patches WHERE id = ?").get(patchId) as
    | { id: number; gap_id: number; repo: string; branch: string; diff_path: string; summary: string; files_touched: number; status: string; created_at: string }
    | undefined;

  if (!row) return res.status(404).json({ error: "patch not found" });

  let diff = "";
  try {
    diff = fs.readFileSync(row.diff_path, "utf8");
  } catch {
    diff = "(patch file not found on disk)";
  }

  res.json({ ...row, diff });
});

/** GET /patches */
patchesRouter.get("/patches", (_req, res) => {
  const rows = db
    .prepare(
      `SELECT p.*, g.canonical_name, g.category, g.missing_in
       FROM patches p
       LEFT JOIN gaps g ON g.id = p.gap_id
       ORDER BY p.id DESC LIMIT 50`,
    )
    .all();
  res.json(rows);
});

// ─── helpers ─────────────────────────────────────────────────────────────────

interface SourceSpec {
  featureName?: string;
  typeDefinition?: string;
  configKey?: string;
  defaultValue?: string;
  behavior?: string;
  allRelatedFiles?: Array<{ path: string; role: string }>;
  reScriptGotchas?: string[];
  implementationSteps?: string[];
}

function buildSpecBasedImplementerPrompt(opts: {
  spec: SourceSpec;
  gap: GapRow;
  repoLabel: string;
  sourceLabel: string;
  sourceDir: string;
  targetDir: string;
  sourceEntryPath: string;
}): string {
  const { spec, gap, repoLabel, targetDir } = opts;
  return `You are implementing a feature in the ${repoLabel} repository.

Your cwd is the TARGET repo: ${targetDir}
You have Edit, Write, Read, Glob, Grep, and Bash tools.

## Feature to implement: ${gap.canonical_name}

A source-code analyst has already fully studied how this feature works in the reference implementation.
Here is their structured spec — follow it exactly:

<spec>
${JSON.stringify(spec, null, 2)}
</spec>

## What to do

1. Use Glob and Grep to understand the TARGET repo's structure. Find the equivalent of each source file listed in spec.allRelatedFiles.
2. Apply spec.implementationSteps in order, adapted to the target repo's idioms and naming conventions.
3. Do NOT copy source code verbatim — the two repos have different architectures.
4. Only touch files that need to change. No unrelated refactors.

## ⛔ HARD REQUIREMENT — build must be green before you finish

After every meaningful batch of edits, run:
  npm run --silent re:build 2>&1
Pass Bash timeout: 240000 (cold builds take up to 120 seconds).

Iterate until exit code 0. There is NO attempt limit — use the full time budget.

When a build fails:
  a. List ALL errors: file path, line number, error message.
  b. Find the root cause — one missing record-field update often produces 3+ error lines.
  c. Fix the root cause first, re-run, then handle remaining secondary errors.

ReScript-specific pitfalls (also see spec.reScriptGotchas):
- Adding a field to a record → EVERY constructor of that record must include it.
  Grep for the record type name BEFORE editing to find all construction sites.
- Optional fields: option<T> with Some(x) / None. Never undefined or null.
- New variants → every switch on that type must be exhaustive.
- Use Belt.Option.getWithDefault, not Option.getOrElse.
- open ModuleName can shadow built-ins — prefer Belt.* qualified names.

## Output (only after build exits 0)

Output ONLY this JSON — no code fences, no extra text:
{"what":"<one-line description>","files":[{"path":"<path relative to target repo>","change":"<brief>"}],"backward_compatible":true,"build_status":"passed","build_attempts":<n>,"notes":"<optional caveats>"}`;
}

function buildFallbackImplementerPrompt(opts: {
  gap: GapRow;
  repoLabel: string;
  sourceLabel: string;
  sourceDir: string;
  targetDir: string;
  sourceEntryPath: string;
}): string {
  const { gap, repoLabel, sourceLabel, sourceDir, targetDir, sourceEntryPath } = opts;
  return `You are implementing a missing feature in the ${repoLabel} repository.

SOURCE repo (${sourceLabel}): ${sourceDir}
TARGET repo: ${targetDir}   ← your cwd

## Feature to implement

Name: ${gap.canonical_name}
Category: ${gap.category}
Rationale: ${gap.rationale}
Starting point in source: ${sourceEntryPath}

## Phase 1 — Understand the feature in the SOURCE repo

Use Read, Grep, and Glob with ABSOLUTE PATHS to explore ${sourceDir}.

1. Start at ${sourceEntryPath}.
2. Follow imports to find EVERY file involved:
   - Type declaration, config parser, state flow, component render
3. Grep ${sourceDir} for "${gap.canonical_name}" variants.
4. State clearly: the TYPE, the config KEY, ALL involved files, BEHAVIOUR.

Do NOT edit the target until Phase 2.

## Phase 2 — Implement in TARGET

Find the target equivalent of each source file and apply the same logical change.
Adapt to target idioms — do NOT copy source code verbatim.

## ⛔ Build must be green — no attempt limit

npm run --silent re:build 2>&1  (Bash timeout: 240000)
Iterate until exit 0.

ReScript: record constructors, option<T>/Some/None, exhaustive switches, Belt.* stdlib.

## Output (after green build)

{"what":"<one-line>","files":[{"path":"<relative>","change":"<brief>"}],"backward_compatible":true,"build_status":"passed","build_attempts":<n>,"notes":"<caveats>"}`;
}

function buildVerifierPrompt(opts: {
  spec: SourceSpec | null;
  gap: GapRow;
  targetDir: string;
  repoLabel: string;
}): string {
  const { spec, gap, targetDir, repoLabel } = opts;
  const specSection = spec
    ? `The source analyst produced this spec:\n\n<spec>\n${JSON.stringify(spec, null, 2)}\n</spec>`
    : `No structured spec is available. Verify by searching for "${gap.canonical_name}" and checking it was added correctly.`;

  return `You are a code reviewer verifying that a feature was implemented correctly.

The server has already confirmed the ReScript build is GREEN — do NOT re-run the build.
Your job is to verify SEMANTIC CORRECTNESS only using Read and Grep.

Feature: ${gap.canonical_name}
Target repo: ${targetDir} (${repoLabel})

${specSection}

## What to verify

${spec ? `
1. TYPE: Find the field in the target repo. Confirm its type matches spec.typeDefinition ("${spec.typeDefinition ?? "?"}").
2. CONFIG KEY: Search for the config key "${spec.configKey ?? gap.canonical_name}" in the parser code. Confirm it's read from the correct config object.
3. DEFAULT: Confirm the default value matches spec.defaultValue ("${spec.defaultValue ?? "?"}").
4. COVERAGE: Check that spec.allRelatedFiles layers are covered — type, parser, at minimum.
` : `
1. Search for "${gap.canonical_name}" in the target repo and confirm it appears in at least 2-3 files (not just one).
2. Confirm there is a config parser that reads the feature from the integrator options.
3. Confirm there is a type declaration for the feature.
`}

## Output

Output ONLY this JSON:
{"pass": true, "issues": []}
— or —
{"pass": false, "issues": ["<specific issue 1>", "<specific issue 2>"]}

Do not output anything else. No prose, no fences.`;
}

function buildSingleAgentPrompt(opts: {
  gap: GapRow;
  targetRepo: RepoKey;
  sourceRepo: RepoKey;
  repoLabel: string;
  sourceLabel: string;
  sourceDir: string;
  targetDir: string;
  sourceFile: string | null;
  sourceContext: string;
}): string {
  const { gap, repoLabel, sourceLabel, sourceDir, targetDir, sourceFile, sourceContext } = opts;
  return `You are implementing a missing feature in the ${repoLabel} repository.

SOURCE repo (${sourceLabel}): ${sourceDir}
TARGET repo: ${targetDir}   ← your cwd

## Feature to implement

Feature name: ${gap.canonical_name}
Category: ${gap.category}
Rationale: ${gap.rationale}

## Reference implementation (from source repo)

File: ${sourceFile ?? "unknown"}

\`\`\`
${sourceContext || "(no source context available)"}
\`\`\`

## Instructions

1. Use Glob and Grep to understand the existing code structure and conventions.
2. Find the right location to add the feature — follow the repo's existing patterns.
3. Implement the feature idiomatically for this repo's architecture.
4. Only touch files that are necessary.

## ⛔ Build must be green

npm run --silent re:build 2>&1  (Bash timeout: 240000)
No attempt limit. Iterate until exit 0.
ReScript: record constructors, option<T>/Some/None, exhaustive switches, Belt.* stdlib.

## Output (after green build)

{"what":"<one-line>","files":[{"path":"<relative>","change":"<brief>"}],"backward_compatible":true,"build_status":"passed","build_attempts":<n>,"notes":"<caveats>"}`;
}

function safeParseEvidence(s: string): Array<{ name?: string; file?: string; snippet?: string }> | null {
  try {
    return JSON.parse(s);
  } catch {
    return null;
  }
}
