import { useState } from "react";
import type { PatchResponse } from "../api";

interface Props {
  patch: PatchResponse;
  gapName: string;
  onClose: () => void;
}

interface StructuredSummary {
  what: string;
  files: Array<{ path: string; change: string }>;
  backward_compatible?: boolean;
  notes?: string;
}

/** Try to parse the summary as structured JSON, fall back to plain text */
function parseSummary(raw: string): StructuredSummary | null {
  try {
    // Try extracting JSON from the raw text (may have surrounding prose)
    const braceStart = raw.indexOf("{");
    const braceEnd = raw.lastIndexOf("}");
    if (braceStart === -1 || braceEnd === -1) return null;
    const json = raw.slice(braceStart, braceEnd + 1);
    const parsed = JSON.parse(json);
    if (parsed.what && Array.isArray(parsed.files)) return parsed;
    return null;
  } catch {
    return null;
  }
}

function generatePrDescription(patch: PatchResponse, gapName: string): string {
  const repoName =
    patch.repo === "web" ? "hyperswitch-web" : "hyperswitch-client-core";
  const structured = parseSummary(patch.summary);
  const title = `feat: add ${gapName} to ${repoName}`;

  let filesSection = `- **Files touched:** ${patch.filesTouched}`;
  if (structured?.files) {
    filesSection = structured.files
      .map((f) => `- \`${f.path}\` — ${f.change}`)
      .join("\n");
  }

  const body = `## Summary

${structured?.what ?? `Adds the \`${gapName}\` feature to **${repoName}**`}

## Changes

${filesSection}

- **Branch:** \`${patch.branch}\`
- **Build status:** ${patch.buildStatus ?? "not checked"}
${structured?.notes ? `\n> ${structured.notes}` : ""}

## Context

This feature already exists in the ${patch.repo === "web" ? "mobile" : "web"} SDK. This PR ports it to maintain feature parity across both SDKs.
${structured?.backward_compatible !== undefined ? `\n**Backward compatible:** ${structured.backward_compatible ? "Yes" : "No"}` : ""}

## Test plan

- [ ] Verify the new feature works as expected
- [ ] Run existing tests to ensure no regressions
- [ ] Compare behavior with the reference implementation in the other SDK
- [ ] Test edge cases specific to this platform

---
*Generated by Feature Gap Dashboard*`;

  return `${title}\n\n${body}`;
}

export function DiffViewer({ patch, gapName, onClose }: Props) {
  const [copiedPr, setCopiedPr] = useState(false);
  const structured = parseSummary(patch.summary);

  const onCopyPr = () => {
    navigator.clipboard.writeText(generatePrDescription(patch, gapName));
    setCopiedPr(true);
    setTimeout(() => setCopiedPr(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4">
      <div className="max-w-4xl w-full max-h-[90vh] flex flex-col rounded-xl border border-slate-700 bg-slate-900 shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-700 px-6 py-4">
          <div>
            <h2 className="text-lg font-semibold text-slate-100">
              Patch: {gapName}
            </h2>
            <p className="text-sm text-slate-400 mt-1">
              Branch: <code className="text-indigo-300">{patch.branch}</code>
              {" · "}
              {patch.filesTouched} file
              {patch.filesTouched === 1 ? "" : "s"} touched
              {" · "}
              {patch.repo} repo
              {" · "}
              <BuildBadge status={patch.buildStatus} />
            </p>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg border border-slate-700 px-3 py-1.5 text-sm text-slate-400 hover:text-slate-200 hover:border-slate-500"
          >
            Close
          </button>
        </div>

        {/* Summary Card */}
        <div className="border-b border-slate-800 px-6 py-4">
          {structured ? (
            <SummaryCard summary={structured} />
          ) : (
            <div className="text-sm text-slate-300">{patch.summary}</div>
          )}
        </div>

        {/* Build log (only shown on failure) */}
        {patch.buildStatus === "fail" && patch.buildLog && (
          <div className="border-b border-red-900/50 bg-red-950/20 px-6 py-3">
            <div className="text-xs font-medium text-red-400 mb-1">
              Build errors:
            </div>
            <pre className="text-xs text-red-300/80 font-mono whitespace-pre-wrap max-h-32 overflow-auto">
              {patch.buildLog}
            </pre>
          </div>
        )}

        {/* Diff */}
        <div className="flex-1 overflow-auto p-4">
          <pre className="text-xs font-mono leading-relaxed whitespace-pre overflow-x-auto">
            {patch.diff.split("\n").map((line, i) => (
              <DiffLine key={i} line={line} />
            ))}
          </pre>
        </div>

        {/* Footer with apply command + PR description */}
        <div className="border-t border-slate-700 px-6 py-3 space-y-2">
          <div className="flex items-center gap-3">
            <span className="text-xs text-slate-500">Apply with:</span>
            <code className="flex-1 rounded bg-slate-800 px-3 py-1.5 text-xs text-slate-300 font-mono">
              cd workspace/
              {patch.repo === "web"
                ? "hyperswitch-web"
                : "hyperswitch-client-core"}{" "}
              && git checkout {patch.branch}
            </code>
            <button
              onClick={() => {
                navigator.clipboard.writeText(
                  `cd workspace/${patch.repo === "web" ? "hyperswitch-web" : "hyperswitch-client-core"} && git checkout ${patch.branch}`,
                );
              }}
              className="rounded border border-slate-700 px-3 py-1.5 text-xs text-slate-400 hover:text-slate-200 hover:border-slate-500"
            >
              Copy
            </button>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-xs text-slate-500">PR ready:</span>
            <span className="flex-1 text-xs text-slate-500">
              Title + description with summary, changes, and test plan
            </span>
            <button
              onClick={onCopyPr}
              className={
                "rounded border px-3 py-1.5 text-xs transition " +
                (copiedPr
                  ? "border-emerald-500 text-emerald-300 bg-emerald-500/10"
                  : "border-slate-700 text-slate-400 hover:text-slate-200 hover:border-slate-500")
              }
            >
              {copiedPr ? "Copied!" : "Copy PR Description"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function SummaryCard({ summary }: { summary: StructuredSummary }) {
  return (
    <div className="space-y-3">
      {/* What */}
      <div className="text-sm font-medium text-slate-100">{summary.what}</div>

      {/* Files table */}
      <div className="rounded-lg border border-slate-800 overflow-hidden">
        <table className="w-full text-xs">
          <thead>
            <tr className="bg-slate-950 text-slate-500 uppercase tracking-wider">
              <th className="text-left px-3 py-2 font-medium">File</th>
              <th className="text-left px-3 py-2 font-medium">Change</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800">
            {summary.files.map((f, i) => (
              <tr key={i} className="hover:bg-slate-800/50">
                <td className="px-3 py-2 font-mono text-indigo-300 whitespace-nowrap">
                  {f.path}
                </td>
                <td className="px-3 py-2 text-slate-400">{f.change}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Metadata row */}
      <div className="flex items-center gap-3 text-xs">
        {summary.backward_compatible !== undefined && (
          <span
            className={
              "inline-flex items-center gap-1 rounded border px-2 py-0.5 font-medium " +
              (summary.backward_compatible
                ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-300"
                : "border-amber-500/30 bg-amber-500/10 text-amber-300")
            }
          >
            {summary.backward_compatible
              ? "\u2713 Backward compatible"
              : "\u26A0 Breaking change"}
          </span>
        )}
        {summary.notes && (
          <span className="text-slate-500">{summary.notes}</span>
        )}
      </div>
    </div>
  );
}

function BuildBadge({ status }: { status?: "pass" | "fail" | "skipped" }) {
  if (!status || status === "skipped") {
    return (
      <span className="inline-block rounded border px-1.5 py-0.5 text-xs font-medium bg-slate-700/20 text-slate-500 border-slate-700">
        build: skipped
      </span>
    );
  }
  if (status === "pass") {
    return (
      <span className="inline-block rounded border px-1.5 py-0.5 text-xs font-medium bg-emerald-500/10 text-emerald-300 border-emerald-500/30">
        build: pass
      </span>
    );
  }
  return (
    <span className="inline-block rounded border px-1.5 py-0.5 text-xs font-medium bg-red-500/10 text-red-300 border-red-500/30">
      build: fail
    </span>
  );
}

function DiffLine({ line }: { line: string }) {
  let color = "text-slate-400";
  if (line.startsWith("+") && !line.startsWith("+++")) {
    color = "text-emerald-400";
  } else if (line.startsWith("-") && !line.startsWith("---")) {
    color = "text-red-400";
  } else if (line.startsWith("@@")) {
    color = "text-indigo-400";
  } else if (line.startsWith("diff ") || line.startsWith("index ")) {
    color = "text-slate-500";
  }
  return <div className={color}>{line || " "}</div>;
}
